"""remove multi user and user table

Revision ID: 37bd8950a64b
Revises: 2b230f913bd6
Create Date: 2025-12-06 14:20:02.810174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bd8950a64b'
down_revision: Union[str, Sequence[str], None] = '2b230f913bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['name'])
    op.drop_constraint(op.f('project_owner_fkey'), 'project', type_='foreignkey')
    op.drop_column('project', 'owner')
    op.create_unique_constraint(None, 'task', ['name'])
    op.drop_table('user')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='unique')
    op.add_column('project', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('project_owner_fkey'), 'project', 'user', ['owner'], ['id'])
    op.drop_constraint(None, 'project', type_='unique')
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('name', name=op.f('user_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
