"""add relations

Revision ID: a9a4c15199f9
Revises: 137c0e86b603
Create Date: 2025-11-26 17:38:40.993329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a4c15199f9'
down_revision: Union[str, Sequence[str], None] = '137c0e86b603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['owner'], ['id'])
    op.add_column('task', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'owner')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'owner')
    # ### end Alembic commands ###
